Added missing types to fix this issue.
npm run build

tsc

node_modules/strict-typed-events/node_modules/ts-gems/lib/types.d.ts:21:17 - error TS2304: Cannot find name 'ReadableStreamGetReaderOptions'.

21 options?: ReadableStreamGetReaderOptions,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/strict-typed-events/node_modules/ts-gems/lib/types.d.ts:22:8 - error TS2552: Cannot find name 'ReadableStreamReader'. Did you mean 'ReadableStream'?

22 ): ReadableStreamReader;
~~~~~~~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: node_modules/strict-typed-events/node_modules/ts-gems/lib/types.d.ts:21