Change module to Node16 as this is require for it to compile due to settings in parent tsconfig.
> ts-gems@3.5.1 compile
> tsc -b tsconfig.json

tsconfig.json:5:15 - error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.

5     "module": "CommonJS",
                ~~~~~~~~~~